#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

mkdir -p logs

blockMesh > logs/blockMesh.log 2>&1

#Copy fields containing boundary value settings
cp -r 0.org 0

setFields > logs/setFields.log 2>&1
interFoam > logs/interFoam.log 2>&1
