#!/bin/sh

export nProc=1
application=interFoam
host=$HOSTNAME

mkdir -p logs

blockMesh > logs/blockMesh.log 2>&1

#Copy fields containing boundary value settings
cp -r 0.org 0

setFields > logs/setFields.log 2>&1

if [ "$nProc" -gt "1" ]; 
then
	decomposePar > logs/decomposePar.log 2>&1
	mpirun -np $nProc --host $host $application -parallel > logs/$application.log 2>&1
else
	$application > logs/$application.log 2>&1
fi
