#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

#Copy fields containing boundary value settings
cp 0.org/alpha1 0/alpha1

runApplication setFields
application2="interFoam"
runApplication $application2